queue_rules:
  - name: shared_queue
    conditions:
      - "#approved-reviews-by>=2"

pull_request_rules:
  - name: automatic merge of hotfix (high priority)
    conditions:
      - "#approved-reviews-by>=2"
      - label=A-bug
      - check-success=stonedb-build
    actions:
      queue:
        name: shared_queue
        method: squash

  - name: put other pr to merge queue
    conditions:
      - "#approved-reviews-by>=2"
      - label!=A-bug
      - check-success=stonedb-build
    actions:
      queue:
        name: shared_queue
        method: squash

  # Check if PR title contain valid types
  - name: Comment PR if title not semantic
    conditions:
          - author!=Mergify
          - 'title!=^(feat|fix|docs|workflow|style|refactor|test|website|chore)(\(.*\))?:'
    actions:
      comment:
        message: |
          This pull request's title should follow requirements next. @{{author}} please check it :point_down:.

          Valid format:

          ```
          fix(vc): fix sth..... (#3306)
            ^         ^---------^  ^----^
            |         |            |
            |         +            +-> you issue id.
            |         |
            |         +-> Summary in present tense.
            |
            +-------> Type: feat, fix, docs, workflow, style, refactor, test, website, chore
          ```

          Valid types:

          - `feat`: new feature for stonedb
          - `fix`: bug fix for stonedb
          - `docs`: changes to the documentation
          - `workflow`: ci/cd in .github
          - `refactor`: refactoring production code, eg. renaming a variable
          - `style`: formatting, missing semi colons, etc; no production code change
          - `test`: adding missing tests, refactoring tests; no production code change
          - `website`
          - `chore`: updating grunt tasks etc; no production code change

# if there is a conflict in a approved PR, ping the author.
  - name: ping author if there is conflicts
    conditions:
      - conflict
      - "#approved-reviews-by >= 2"
    actions:
      comment:
        message: |
          This pull request has merge conflicts, you should resolve it before merged. @{{author}} please update it :)

          Try `@mergify update` or update manually.

  - name: Welcome new contributor
    conditions:
      - author!=Mergify
    actions:
      comment:
        message: |
          Thanks for the contribution!
          I have applied any labels matching special text in your PR Changelog.

          Please review the labels and make any necessary changes.

  # Assign pr label based of tags
  - name: label on New Feature
    conditions:
      - 'title~=^(feat)(\(.*\))?:'
    actions:
      label:
        add:
          - PR-feature
  - name: label on Bug Fix
    conditions:
      - 'title~=^(fix)(\(.*\))?:'
    actions:
      label:
        add:
          - PR-bug
  - name: label on docs
    conditions:
      - 'title~=^(docs)(\(.*\))?:'
    actions:
      label:
        add:
          - PR-docs
  - name: label on style
    conditions:
      - 'title~=^(style)(\(.*\))?:'
    actions:
      label:
        add:
          - PR-style
  - name: label on Refactor
    conditions:
      - 'title~=^(refactor)(\(.*\))?:'
    actions:
      label:
        add:
          - PR-refactor
  - name: label on test
    conditions:
      - 'title~=^(test)(\(.*\))?:'
    actions:
      label:
        add:
          - PR-testing
  - name: label on chore
    conditions:
      - 'title~=^(chore)(\(.*\))?:'
    actions:
      label:
        add:
          - PR-chore
